maximum_email_length: 255
maximum_name_length: 50
minimum_password_length: 6
gravatar_size: 80
one: "1"
user_size_gravatar: 50
per_pages: 10
modelss:
  micropost_maximum: 140
  micropost_byte: 5
upload_size_limit: 400
views_number:
  shows_size: 30
